# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc 
  namespace: n8n 
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

